web/router.ex
defmodule GreatQuestionsTo.Router do
  use GreatQuestionsTo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GreatQuestionsTo do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/dashboard", DashboardController, :index
    get "/questionario", QuestionnaireController, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", GreatQuestionsTo do
  #   pipe_through :api
  # end
end

lib/great_questions_to/endpoint.ex
defmodule GreatQuestionsTo.Endpoint do
  use Phoenix.Endpoint, otp_app: :great_questions_to

  if Application.get_env(:great_questions_to, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  socket "/socket", GreatQuestionsTo.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :great_questions_to, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt semantic themes)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_great_questions_to_key",
    signing_salt: "g5GzhQc+"

  plug GreatQuestionsTo.Router
end

lib/great_questions_to/repo.ex
defmodule GreatQuestionsTo.Repo do
  use Ecto.Repo, otp_app: :great_questions_to
end

web/controllers/dashboard_controller.ex
defmodule GreatQuestionsTo.DashboardController do
  use GreatQuestionsTo.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/page_controller.ex
defmodule GreatQuestionsTo.PageController do
  use GreatQuestionsTo.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/questionnaire_controller.ex
defmodule GreatQuestionsTo.QuestionnaireController do
  use GreatQuestionsTo.Web, :controller

  def new(conn, params) do
    render conn, "new.html"
  end
end

web/views/dashboard_view.ex
defmodule GreatQuestionsTo.DashboardView do 
  use GreatQuestionsTo.Web, :view

end

web/views/error_view.ex
defmodule GreatQuestionsTo.ErrorView do
  use GreatQuestionsTo.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule GreatQuestionsTo.LayoutView do
  use GreatQuestionsTo.Web, :view
end

web/views/page_view.ex
defmodule GreatQuestionsTo.PageView do
  use GreatQuestionsTo.Web, :view
end

web/views/questionnaire_view.ex
defmodule GreatQuestionsTo.QuestionnaireView do
  use GreatQuestionsTo.Web, :view

end

web/templates/dashboard/index.html.eex
<style>

  .ui.vertical.stripe{
    padding: 2em 0em;
    border: 0;
  }

  .four.centered.column{
    padding: 0 !important;
    width: auto !important;
  }

  .ui.statistic>.value{
    color: #BFB2C5;
  }

  .ui.statistic>.label{
    color: #2E235E;
  }

  .button>a{
    color: #6435c9!important;
  }

  .ui.segments{
    border: 0 !important;
    box-shadow: 0 5px 21px 0 rgba(34,36,38,.15);
    /*box-shadow: 0 42px 64px 0 #e7e7ec; Unibank example */
  }

  .ui.segment{
    border: 0 !important;
  }

  .ui.purple.button{
    color: #a33888 !important;
  }

  .ui.pointing.label{
    color: #a33888 !important;
    border-color: #a33888 !important;
  }

  .list>.item>.content>.header{
    color: #382063;
    font-weight: 100 !important;
  }

  .list>.item>.content>.subheader{
    color: #BFB2C5;
    /*color: #999295;*/
  }

  tr>.header,.subheader{
    border: none !important;
  }

  .hd-pink{
    color: #a33888!important;
  }

  .subheader-gray{
    color: #999;
  }

  .ui.two.column.grid.container{
    width: 100%!important;
  }

  .with-padding{
    padding-left: 1.5em!important;
    padding-top: 0.5em!important;
  }

  .ui.items:not(.unstackable)>.item{
    flex-direction: row!important;
  }

  #questionnaire-count,#team-count{
    font-size: 4rem!important;
  }

  #questionnaires-overview,#team-overview{
    box-shadow: 0 5px 21px 0 rgba(34,36,38,.15);
  }
  
  @media (max-width: 991px){
    .research-support{
      margin-top: 2rem!important;
    }
  }
  @media only screen and (max-width: 767px){

    .ui.two.column.grid.container{
      width: auto!important;
    }

    .ui.middle.aligned.stackable.grid.container{
      text-align: center;
    }

    .ui.stackable.grid>.row>.column{
      margin-left: auto !important;
      margin-right: auto !important;
      width: auto !important;
    }

    .ui.table:not(.unstackable) tbody{
      display: table-row-group!important;
    }

    .ui.table:not(.unstackable) tr{
      display: table-row-group!important;
      border: 0 !important;
      box-shadow: none !important;
    }

    .ui.table:not(.unstackable) tr>td{
      display: table-cell!important;
    }

    #stats-table{
      line-height: 2rem!important;
    }
  }

  @media (max-width: 600px){
    .ui.statistic>.value{
      font-size: 2rem !important;
    }

    .ui.statistic>.label{
      font-size: .8rem !important;
    }
  }

  @media(max-width: 587px){
    #research-img{
      display:none !important;
    }

    #stats-table{
      width: 100% !important;
    }
  }

  @media(max-width: 500px){
    .ui.stackable.grid>.row>.column{
      width: 50% !important;
    }
  }

  @media(max-width: 483px){
    #collected-questionnaires, #export-questionnaires{
      width:100%!important;
    }

    #export-questionnaires{
      margin-top: 1em!important;
    }
  }
  
</style>

<section class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">

      <article class="four centered column">
        <div class="ui statistic">
          <div class="value">
            15
          </div>
          <div class="label">
            Pesquisadores
          </div>
        </div>
      </article>
      
      <article class="four centered column">
        <div class="ui statistic">
          <div class="value">
            10
          </div>
          <div class="label">
            Questionários
          </div>
        </div>
      </article>
      
      <article class="four centered column">
        <div class="ui statistic">
          <div class="value">
            122
          </div>
          <div class="label">
            Entrevistados
          </div>
        </div>
      </article>
      
      <article class="four centered column">
        <div class="ui statistic">
          <div class="value">
            67
          </div>
          <div class="label">
            Dias decorridos
          </div>
        </div>
      </article>
    </div>
  </div>
</section>
  
<div class="ui two column grid container">
  <div class="stretched row">
    <section id="research-overview" class="sixteen wide tablet ten wide computer column">

      <div class="ui segments">
        <div class="ui segment">
          <div class="ui two wide equal width column grid">
            <div class="column">
              <h3 class="ui header">Pesquisa
                <span class="sub header">Visão Geral</span>
              </h3>
            </div>
            <div class="column">

              <div class="ui violet basic right floated icon button" tabindex="0">
                <i class="comments icon"></i>
                <a id="new_interview" href="#">Entrevista</a>
              </div>

            </div>
          </div>
        </div>

        <div class="ui segment" style="padding-top: 2rem; padding-bottom: 2rem;">

          <div class="ui two column grid container">

            <table id="stats-table" class="ui very basic collapsing table ten wide column" style="font-size: .9em;padding:0;">
              <tbody>
                <tr>
                  <td class="header" style="color:#073872;">Entrevistas realizadas:</td>
                  <td class="subheader subheader-gray">122</td>
                </tr>
                <tr>
                  <td class="header" style="color:#073872;">Questionários coletados:</td>
                  <td class="subheader subheader-gray">300</td>
                </tr>
                <tr>
                  <td class="header" style="color:#073872;">Último coletador:</td>
                  <td class="subheader subheader-gray">Denise Marques</td>
                </tr>
                <tr>
                  <td class="header" style="color:#073872;">Última coleta:</td>
                  <td class="subheader subheader-gray">20/04/2018 - 15:17</td>
                </tr>
                <tr>
                  <td class="header" style="color:#073872;">Coletas não finalizadas:</td>
                  <td class="subheader subheader-gray">22</td>
                </tr>
                <tr>
                  <td class="header" style="color:#073872;">Início da pesquisa:</td>
                  <td class="subheader subheader-gray">05/02/2018</td>
                </tr>
                <tr>
                  <td class="header" style="color:#073872;">Dias decorridos:</td>
                  <td class="subheader subheader-gray">67</td>
                </tr>
              </tbody>
            </table>

            <img id="research-img" class="ui image right floated column" src="css/themes/default/assets/images/research-comm.png" style="width:25%;height:25%;padding:0;min-width:136px;min-height:136px;filter: hue-rotate(220deg);">
          </div>

        </div>

        <div class="ui right aligned segment">

          <div id="collected-questionnaires" class="ui basic violet icon button" tabindex="0">
            <i class="unhide icon"></i> 
            <a id="see_all_applied" href="#">Questionários realizados</a>
          </div>

          <div id="export-questionnaires" class="ui basic violet icon button" tabindex="0">
            <i class="upload icon"></i> 
            <a id="export_questionnaires" href="#">Exportar questionários</a>
          </div>

        </div>

      </div>
    </section>

    <div class="research-support sixteen wide tablet six wide computer column">
      <section id="questionnaires-overview" class="ui segment">
        <div class="ui items">
          <div class="item">
            <div class="ui statistic">
              <div id="questionnaire-count" class="value">10</div>
            </div>

            <div class="content with-padding">
              <div class="header hd-pink">Questionários criados</div>
              <div class="meta">
                <span class="price subheader-gray">5</span>
                <span class="stay subheader-gray">sendo usado na pesquisa</span>
              </div>
              <div class="description">
                <p>Os questinários criados aqui servem para mover o conhecimento da humanidade um pouco mais pra frente</p>
              </div>
            </div>
          </div>
            <div class="ui right floated basic violet icon button" tabindex="0">
              <i class="add icon"></i> 
              <a id="add-questionnaire" href="<%= questionnaire_path(@conn, :new) %>">Questionário</a>
            </div>
            <div class="ui right floated basic violet icon button" tabindex="0">
              <i class="unhide icon"></i> 
              <a id="show-questionnaires" href="#">Existentes</a>
            </div>
        </div>
      </section>

      <section id="team-overview" class="ui segment">
        <div class="ui items">
          <div class="item">
            <div class="ui statistic">
              <div id="team-count" class="value">15</div>
            </div>
            <div class="content with-padding">
              <div class="header hd-pink">Pesquisadores</div>
              <div class="meta">
                <span class="price subheader-gray">5</span>
                <span class="stay subheader-gray">ativos na última semana</span>
              </div>
              <div class="description">
                <p>Aqui tem que escrever alguma coisa bem interessante para colocar no lugar daqui</p>
              </div>
              
            </div>
          </div>
          <div class="ui right floated basic violet icon button" tabindex="0">
            <i class="add icon"></i> 
            <a id="add-researcher" href="#">Pesquisador</a>
          </div>
            <div class="ui right floated basic violet icon button" tabindex="0">
              <i class="unhide icon"></i> 
              <a id="researchers" href="#">Ver todos</a>
            </div>
        </div>
      </section>  
    </div>
  </div>
</div>

<script>
  $('.ui.inline.dropdown').dropdown();
</script>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello GreatQuestionsTo!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/semantic.min.css") %>">

    <script src="<%= static_path(@conn, "/js/turbolinks.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/semantic.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/newfile.js") %>"></script>

    <script> 
      $(function(){
      });
    </script>

  </head>

  <style>
    .principal-logo{
      color: #2e235e;
    }

    .secondary-logo{
      color: #a0408f;
    }

    .ui.huge.menu{
      font-size: 1em;
      min-height: 80px;
      border: 0;
      box-shadow: none;
      margin: 0;
    }

    i.circular.icon{
      padding: 0 !important;
      padding-top: .5em !important;
    }

    .user-call{
      padding: 0!important;
    }

    .user-call-in-menu{
      color: #a33888 !important;
      text-align: center !important;
      border: none!important;
      box-shadow: none!important;
    }

    .user-call-in-menu-with-margin{
      color: #a33888!important;
      text-align: center!important;
      border: none!important!;
      box-shadow: none!important;
      margin-right: 1.5em!important;
    }

    .ui.header{
      color: #a33888 !important;
    }

    @media (max-width: 767px){
      .header{
        font-weight: 100!important;
      }
    }
    
  </style>

  <body style="background-color:#F4F5F8;">
    <div class="pusher">
      <header class="ui borderless huge menu">
        <h2 class="ui header small item">
          <!--<i class="settings icon logo"></i>-->
          <i class="users icon"></i>
          <div class="content principal-logo">
            Great Questions Club
            <div class="sub header secondary-logo">Questions that matter</div>
          </div>
        </h2>

        <nav class="menu right">
          <span class="user-call item">
            <a id="see_profile" href="/"><i class="large user-call-in-menu-with-margin circular student icon"></i></a>
            <a id="log_out" href="/"><i class="large user-call-in-menu power icon"></i></a>
          </span>
        </nav>
      </header>

      <main class="container">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
  </body>
</html>

web/templates/page/index.html.eex
<div class="ui cards">
  <div class="card">
    <div class="content">
      <img class="right floated mini ui image" src="/images/avatar/large/elliot.jpg">
      <div class="header">
        Elliot Fu
      </div>
      <div class="meta">
        Friends of Veronika
      </div>
      <div class="description">
        Elliot requested permission to view your contact details
      </div>
    </div>
    <div class="extra content">
      <div class="ui two buttons">
        <div id="btn-green" class="ui basic green button">Approve</div>
        <div class="ui basic red button">Decline</div>
      </div>
    </div>
  </div>
</div>


<div class="ui three column center aligned divided grid container">
  <div class="row">
    <div class="column">
      <div class="ui vertical fluid menu">
        <div class="header item">Primeira Coluna</div>
      </div>
    </div>
    <div class="column">
      <div class="header item">Segunda Coluna</div>
    </div>
    <div class="column">
      <div class="header item">Terceira Coluna</div>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <div class="header item">Quarta Coluna</div>
    </div>
    <div class="column">
      <div class="header item">Quinta Coluna</div>
    </div>
    <div class="column">
      <div class="header item">Sexta Coluna</div>
    </div>
  </div>
</div>

web/templates/questionnaire/new.html.eex
<style>
  .for-small{
    position: fixed;
    bottom: 0!important;
    min-height: 40px!important;
    overflow: hidden;
    margin: 0!important;
  }

  .for-small>.item>.plus, .trash, .bars{
    font-size: 1.7rem!important;
    color: #a33888;
  }

  .ui.purple.segment{
    box-shadow: 0 5px 21px 0 rgba(34,36,38,.15)!important;
  }

  .ui.segment{
    border: none;
    box-shadow: none;
  }

  .instrument{
    margin: 0!important;
  }

  .with-bottom-margin{
    margin-bottom: 1rem!important;
  }

  .with-top-margin{
    margin-top: 3rem!important;
  }

  .instrument-input{
    border-top: none!important;
    border-left: none!important;
    border-right: none!important;
    border-radius: 0!important;
  }

  .card-10clouds{
    border: none!important;
    box-shadow: 0 5px 21px 0 rgba(34,36,38,.15)!important;
  }

  .to-right{
    text-align: right;
  }

  .dark-violet{
    color: #2e235e!important;
  }
      

</style>

<section class="ui stackable two column centered grid instrument">
  <div class="column">

    <div class="ui large form">
      <div class="field with-bottom-margin">
        <label class="dark-violet">Questionário</label>
        <input type="text" class="card-10clouds" placeholder="Insira a descrição do questionário">
      </div>
    </div>

    <div class="to-right">
      <div class="ui slider checkbox">
        <input type="checkbox" id="eliminatory_instrument" name="eliminatory-instrument">
        <label for="eliminatory_instrument">É eliminatório?</label>
      </div>  
    </div>

    <h5 class="ui horizontal divider header ">
      Questões
    </h5>

    <div id="questions">

      <section class="ui purple segment question">
        <div class="ui large form">
          <div class="field with-bottom-margin">
            <input type="text" class="instrument-input" placeholder="Questão..." data-action="selectAllText">
          </div>
        </div>
      </section>

    </div>

  </div>
</section>

<div id="menu" class="ui three item icon menu for-small">
  <a data-action="addNewQuestion" class="item">
    <i data-action="addNewQuestion" class="plus circle icon"></i>
  </a>
  <a id="removeSelectedQuestion" class="item" data-action="proccessRemotionOfSelectedQuestion">
    <i class="trash alternate outline icon" data-action="proccessRemotionOfSelectedQuestion"></i>
  </a>
  <a class="item" data-action="openQuestionOptions">
    <i class="bars icon" data-action="openQuestionOptions"></i>
  </a>
</div>

<div class="ui modal">
  <div class="ui header">
      Opções
  </div>
  <div class="content">

    <div class="ui form">

      <label class="dark-violet">Tipo da Questão</label>
      <div class="grouped fields">

        <div class="field">
          <div class="ui slider checkbox">
            <input id="single-choice" type="radio" name="whatever" checked="checked">
            <label for="single-choice">Escolha única</label>
          </div>
        </div>
        <div class="field">
          <div class="ui slider checkbox">
            <input id="multiple-choice" type="radio" name="whatever">
            <label for="multiple-choice">Múltipla escolha</label>
          </div>
        </div>
        
      </div>
    </div>
    
  </div>

  <div class="actions">
    <div class="buttons">
      <div class="ui violet cancel inverted button">
        <i class="remove icon"></i>
        Cancelar
      </div>
      <div class="ui violet ok inverted button">
        <i class="checkmark icon"></i>
        Configurar
      </div>
    </div>
  </div>

</div>

<script>
  const addClickListenerOn = (element, toExecuteThisFunction) => element.addEventListener('click', toExecuteThisFunction);
  const containerWithIdOf = (elements) => document.getElementById(elements);

  function toMakeTheInnerQuestionClickedTheActiveOne(event){
    deactivate(currentActiveQuestion());
    activate(newCurrentQuestionInThis(event));
  }

  const deactivate = (component) => component ? component.classList.remove('purple') : null;
  const currentActiveQuestion = () => document.getElementsByClassName('purple')[0];
  const activate = (component) => component ? component.classList.add('purple') : null;
  const newCurrentQuestionInThis = (event) => event.target.closest('.question');

  addClickListenerOn(containerWithIdOf('questions'), toMakeTheInnerQuestionClickedTheActiveOne);

  //Implement behaviors to configure the question being created
  addClickListenerOn(containerWithIdOf('questions'), toTakeActionsToConfigureTheQuestionBeingCreated);

  function toTakeActionsToConfigureTheQuestionBeingCreated(event){
    if (!event.target.dataset.action) return;
    window[`${event.target.dataset.action}`](event.target);
  }

  function selectAllText(element){
    element.select();
  }

  //End the configuration of questions being created


  //End of Turn the question the active one

  //function that execute the actions on questions like add or remove
  function toTakeActionsOnQuestionsBeingCreated(event){
    if (!event.target.dataset.action) return;
    window[`${event.target.dataset.action}`](event);
  }
  
  //end of executioner

  //creation of new question
  function addNewQuestion(event){
    const questions = containerWithIdOf('questions');
    const newQuestion = buildNewQuestion();

    if(currentActiveQuestion()){
      questions.insertBefore(newQuestion, currentActiveQuestion().nextSibling);
      deactivate(currentActiveQuestion());
    }else{
      questions.appendChild(newQuestion);
    }
  }
  
  function createQuestionWrapper(){
    element = document.createElement('section');
    element.setAttribute('class', 'ui purple segment question');
    return element;
  }

  function createQuestionElementsContainer(){
    const questionFormElements = document.createElement('div');
    questionFormElements.setAttribute('class', 'ui large form');
    return questionFormElements;
  }

  function createQuestionDescriptionContainer(){
    const questionField = document.createElement('div');
    questionField.setAttribute('class', 'field with-bottom-margin');
    return questionField;
  }

  function createQuestionDescriptionInput(){
    const questionInput = document.createElement('input');
    questionInput.setAttribute('type', 'text');
    questionInput.setAttribute('class', 'instrument-input');
    questionInput.setAttribute('placeholder', 'Questão...');
    questionInput.setAttribute('data-action', 'selectAllText');
    return questionInput;
  }

  function buildNewQuestion(){
    const uiQuestion = createQuestionWrapper();
    const questionFormElements = createQuestionElementsContainer();
    const questionField = createQuestionDescriptionContainer();
    const questionInput = createQuestionDescriptionInput();

    questionField.appendChild(questionInput);
    questionFormElements.appendChild(questionField);
    uiQuestion.appendChild(questionFormElements);

    return uiQuestion;
  }
  
  //end creation of new question

  const thereIsNoCurrentActiveQuestion = () => currentActiveQuestion() ? false : true;

  function proccessRemotionOfSelectedQuestion(event){
    if (thereIsNoCurrentActiveQuestion()) return;
    let previousSiblingOfQuestionBeingRemoved = currentActiveQuestion().previousElementSibling;
    currentActiveQuestion().remove();
    activate(previousSiblingOfQuestionBeingRemoved);
  }

  function openQuestionOptions(event){
    $('.ui.modal').modal('show');
  }
  
  addClickListenerOn(containerWithIdOf('menu'), toTakeActionsOnQuestionsBeingCreated);
</script>